project:
  type: book

  output-dir: docs

book:
  title: "Rust for R Developers"
  subtitle: Cascadia R Conference, 2025
  author:
    - "Josiah Parry"
    - "Mossa Merhi Reimert, PhD"
  date: "2025-06-20"
  site-url: https://josiahparry.github.io/2025-cascadia-rust-for-r-devs/
  repo-url: https://github.com/JosiahParry/2025-cascadia-rust-for-r-devs/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: intro-to-rust-for-r-devs/index.qmd
      chapters:
        # - intro-to-rust-for-r-devs/index.qmd
        - intro-to-rust-for-r-devs/01-why-rust.qmd
        - intro-to-rust-for-r-devs/02-hello-world.qmd
        - intro-to-rust-for-r-devs/03-types.qmd
        - intro-to-rust-for-r-devs/04-fizz-buzz.qmd
        - intro-to-rust-for-r-devs/05-collections.qmd
        - intro-to-rust-for-r-devs/06-for-loops.qmd
        - intro-to-rust-for-r-devs/07-mutability.qmd
        - intro-to-rust-for-r-devs/08-mutable-vectors.qmd
        - intro-to-rust-for-r-devs/09-is-odd.qmd
        - intro-to-rust-for-r-devs/10-references-slices.qmd
        - intro-to-rust-for-r-devs/11-iterators.qmd
        - intro-to-rust-for-r-devs/12-iter-map.qmd
        - intro-to-rust-for-r-devs/13-structs.qmd
        - intro-to-rust-for-r-devs/14-struct-methods.qmd
        - intro-to-rust-for-r-devs/15-enums.qmd
        - intro-to-rust-for-r-devs/16-options.qmd
        - intro-to-rust-for-r-devs/17-result.qmd
        - intro-to-rust-for-r-devs/18-anyhow.qmd
        # - intro-to-rust-for-r-devs/parallelize.qmd
    - part: building-rust-based-r-pkgs/index.qmd
      chapters:
        - building-rust-based-r-pkgs/ffi.qmd
        - building-rust-based-r-pkgs/extendr.qmd
        - building-rust-based-r-pkgs/objective.qmd
        - building-rust-based-r-pkgs/hello-world.qmd
        - building-rust-based-r-pkgs/extendr-structure.qmd
        - building-rust-based-r-pkgs/extendr-dx.qmd
        - building-rust-based-r-pkgs/rust-deps.qmd
        - building-rust-based-r-pkgs/first-fn.qmd
        - building-rust-based-r-pkgs/encode.qmd
        - building-rust-based-r-pkgs/throwing-errors.qmd
        - building-rust-based-r-pkgs/vectorize.qmd
        - building-rust-based-r-pkgs/r-type-system.qmd
        - building-rust-based-r-pkgs/using-extendr-types.qmd
        - building-rust-based-r-pkgs/error-handling.qmd
        - building-rust-based-r-pkgs/na-handling.qmd
        - building-rust-based-r-pkgs/enums.qmd
        - building-rust-based-r-pkgs/geohash-nb.qmd
        - building-rust-based-r-pkgs/vectorize-neighbor.qmd
        - building-rust-based-r-pkgs/decode.qmd
        - building-rust-based-r-pkgs/vectorize-decode.qmd
        - building-rust-based-r-pkgs/vibe-check.qmd

format:
  html:
    theme:
      - cosmo
    # number-sections: false
    number-depth: 1
    highlight-style: github
    callout-appearance: simple
