project:
  type: book

  output-dir: docs

book:
  title: "Rust for R Developers"
  subtitle: Cascadia R Conference, 2025
  author:
    - "Josiah Parry"
    - "Mossa Merhi Reimert, PhD"
  date: "2026-06-26"
  site-url: https://josiahparry.github.io/rust-for-r-devs/
  repo-url: https://github.com/JosiahParry/rust-for-r-devs/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: intro-to-rust-for-r-devs/index.qmd
      chapters:
        # - intro-to-rust-for-r-devs/index.qmd
        - intro-to-rust-for-r-devs/01-why-rust.qmd
        - intro-to-rust-for-r-devs/02-hello-world.qmd
        - intro-to-rust-for-r-devs/03-types.qmd
        - intro-to-rust-for-r-devs/04-fizz-buzz.qmd
        - intro-to-rust-for-r-devs/05-collections.qmd
        - intro-to-rust-for-r-devs/06-for-loops.qmd
        - intro-to-rust-for-r-devs/07-mutability.qmd
        - intro-to-rust-for-r-devs/08-mutable-vectors.qmd
        - intro-to-rust-for-r-devs/09-is-odd.qmd
        - intro-to-rust-for-r-devs/10-references-slices.qmd
        - intro-to-rust-for-r-devs/11-iterators.qmd
        - intro-to-rust-for-r-devs/12-iter-map.qmd
        - intro-to-rust-for-r-devs/13-structs.qmd
        - intro-to-rust-for-r-devs/14-struct-methods.qmd
        - intro-to-rust-for-r-devs/15-enums.qmd
        - intro-to-rust-for-r-devs/16-options.qmd
        - intro-to-rust-for-r-devs/17-result.qmd
        - intro-to-rust-for-r-devs/18-anyhow.qmd
        # - intro-to-rust-for-r-devs/parallelize.qmd
    - part: building-rust-based-r-pkgs/index.qmd
      chapters:
        - building-rust-based-r-pkgs/01-ffi.qmd
        - building-rust-based-r-pkgs/02-what-is-extendr.qmd
        - building-rust-based-r-pkgs/03-objective.qmd
        - building-rust-based-r-pkgs/04-hello-world.qmd
        - building-rust-based-r-pkgs/05-package-structure.qmd
        - building-rust-based-r-pkgs/06-extendr-dx.qmd
        - building-rust-based-r-pkgs/07-use-crate-url.qmd
        - building-rust-based-r-pkgs/08-r-type-system.qmd
        - building-rust-based-r-pkgs/09-new-type-struct.qmd
        - building-rust-based-r-pkgs/10-external-pointers.qmd
        - building-rust-based-r-pkgs/11-vectorization.qmd
        - building-rust-based-r-pkgs/12-na-handling.qmd
        - building-rust-based-r-pkgs/13-print-helper.qmd
        - building-rust-based-r-pkgs/14-s3.qmd
        - building-rust-based-r-pkgs/15-url-getters.qmd
        - building-rust-based-r-pkgs/16-mapping-into-option.qmd
        - building-rust-based-r-pkgs/17-setters-cow.qmd
        - building-rust-based-r-pkgs/18-combining-iterators.qmd
        - building-rust-based-r-pkgs/19-recycling-and-errors.qmd
        - building-rust-based-r-pkgs/20-query-pairs.qmd
        - building-rust-based-r-pkgs/21-roxygen-docs.qmd
        - building-rust-based-r-pkgs/22-cran.qmd

format:
  html:
    theme:
      - cosmo
    # number-sections: false
    number-depth: 1
    highlight-style: github
    callout-appearance: simple
