# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib shortuuid, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

# nolint end
