# Workshop Scope

::: callout-tip
## Objective

Define the scope and objective of the workshop.

:::

There's no better way to learn than by doing.

In this workhop we will learn how to use extendr and create Rust-powered R package by creating a new package called `{geohashrs}`. The `{geohashrs}` R package will provide R bindings to the [geohash crate](https://docs.rs/geohash).

Throughout the workshop we will touch on:

- Advanced R topics
- Rust concepts
- Techniques for bridging the two

As much as this is about Rust, we are also working within the confines of R and thus, the two are inextricably linked.

## What is geohashing?

- Geohashes are a way to encode a location on earth as a string of 1 - 12 characters.
- The more shared characters there are between two geohashes, the closes in physical space the geohashes are.
- Used to find approximately near locations.
- Used frequently in databases and web development to quickly query results.


<iframe width="560" height="315" src="https://www.youtube.com/embed/vGKs-c1nQYU?si=J-svZEFWWLsTXWmK" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## The R package

The R package we will create will help us:

- encode geohashes
- find geohash neighbors
- decoded geohash to x & y plus error terms
- decode geohash into a bounding box
