# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib rurls, .registration = TRUE
NULL

url_parse <- function(x) .Call(wrap__url_parse, x)

format_rurls <- function(x) .Call(wrap__format_rurls, x)

url_host <- function(url) .Call(wrap__url_host, url)

url_scheme <- function(url) .Call(wrap__url_scheme, url)

url_path <- function(url) .Call(wrap__url_path, url)

url_port <- function(url) .Call(wrap__url_port, url)

url_query <- function(url) .Call(wrap__url_query, url)

url_authority <- function(url) .Call(wrap__url_authority, url)

url_domain <- function(url) .Call(wrap__url_domain, url)

url_join <- function(url, segment) .Call(wrap__url_join, url, segment)

url_path_segments <- function(url) .Call(wrap__url_path_segments, url)

url_set_host <- function(url, host) .Call(wrap__url_set_host, url, host)

url_set_path <- function(url, path) .Call(wrap__url_set_path, url, path)

url_set_port <- function(url, port) .Call(wrap__url_set_port, url, port)

url_set_scheme <- function(url, scheme) .Call(wrap__url_set_scheme, url, scheme)

url_query_pairs <- function(url) .Call(wrap__url_query_pairs, url)

RUrl <- new.env(parent = emptyenv())

RUrl$new <- function(url) .Call(wrap__RUrl__new, url)

RUrl$get_extptr <- function(robj) .Call(wrap__RUrl__get_extptr, robj)

RUrl$clone_from_robj <- function(robj) .Call(wrap__RUrl__clone_from_robj, robj)

#' @export
`$.RUrl` <- function (self, name) { func <- RUrl[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RUrl` <- `$.RUrl`

# nolint end
