# Handle NAs gracefully

::: callout-tip
## Objective

Understand how to detect NA values in input vectors and produce them in output.

:::


We've been using `xi.inner()` to access the `f64` value of an `Rfloat`. This is an **infallible** method. It always provides the inner value of the `Rfloat`. However, we may want to handle NA values differently.

To handle `NA` values _explicitly_, we can check for the pressence of `NA` in an `Rfloat` using `xi.is_na()`. We can then `match` on the boolean value and choose what to do!

`match` isn't only for enums! When we `match` on booleans, there are only two variants: `true` or `false`. We can also perform nested match statements!

## Example

Here we perform a nested match statement on the `Result` from parsing a string slice to an integer.

```rust
let num_parsed = "10".parse::<i32>();

match num_parsed {
    Ok(num) => {
        match num > 10 {
            true => println!("Parsed number is greater than 10!"),
            false => println!("Parsed number is less than or equal to 10")
        }
    },
    Err(e) => println!("Failed to parse number with error: {e:?}")
}
```

## The pattern

For each element, if it is missing return an `NA`, otherwise do the work.

```rust
#[extendr]
fn add_one(x: Doubles) -> Doubles {
    x.into_iter()
        .map(|xi| {
            match xi.is_na() {
                true => Rfloat::na(),
                false => Rfloat::from(xi.inner() + 1.0),
            }
        })
        .collect::<Doubles>()
}
```

We'll put this pattern to use in the warm-up exercises that follow.
